baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'AI Pilipinas'

google_analytics_id: null
homepage:
  show_call_box: false
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Copyright © 2020'

seo:
  meta_og_title: "AI Pilipinas"
  meta_og_type: "website"
  meta_og_url: "https://www.aipilipinas.org"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "AI Pilipinas is a tech community which aims to share knowledge amongsts its members to help upskill Filipinos on Machine Learning and Artificial Intelligence. The group is run by a group of volunteers."
  # meta_twitter_card: "summary"
  # meta_twitter_site: "@zerostaticio"
  # meta_twitter_creator: "@zerostaticio"

collections:
  events:
    output: true
    permalink: /events/:path/

defaults:
  - scope:
      type: events
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
